Interface not found: DBus::Error instead of nil (and then NoMethodError)
The example below would be correct if it said
`unit_o["org.freedesktop.systemd1.Unit"]`.

With the wrong interface name, `unit_i` used to become `nil` and you
would get an unhelpful
"NoMethodError: undefined method `[]' for nil:NilClass" later.

With this fix, it raises
"DBus::Error: no such interface `Unit' on object `/org/freedesktop/systemd1/unit/_2d_2emount'"

```rb
bus = DBus::SystemBus.instance
svc = bus.service("org.freedesktop.systemd1")
unit_o = svc["/org/freedesktop/systemd1/unit/_2d_2emount"]
unit_i = unit_o["Unit"]  # BUG
descr = unit_i["Description"]
```