Fix connection in case of multiple keyring cookies
If ~/.dbus-keyrings/org_freedesktop_general has multiple cookies, the
matching fails.

Rubocop suggested to introduce a bug: String#index returns a nilable
number, so `== 0` was correct and `.zero?` is not.

Also improved the report in case any other exception happens:

Oops:
undefined method `zero?' for nil:NilClass

        if line.index(id).zero?
                         ^^^^^^
Error: Could not establish connection to: , will now exit.

Now it says
Error: Could not establish connection to: 127.0.0.1:40243, will now exit.